---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "payment-processor-config"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "payment-processor"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.payment_processor.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.payment_processor.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.payment_processor.port_http }}"
  EVENTBUS_HOST: "{{ .Values.config.payment_processor.EVENTBUS_HOST }}"
  EVENTBUS_PORT: "{{ .Values.config.payment_processor.EVENTBUS_PORT }}"
  EVENTBUS_USERNAME: "{{ .Values.config.payment_processor.EVENTBUS_USERNAME }}"
