---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "webhooks-api-secrets"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "webhooks-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__eventbus: "amqp://guest:{{ .Values.secrets.webhooks_api.eventbus_password }}@eventbus-service:5672"
  EVENTBUS_PASSWORD: "{{ .Values.secrets.webhooks_api.eventbus_password }}"
  EVENTBUS_URI: "amqp://guest:{{ .Values.secrets.webhooks_api.eventbus_password }}@eventbus-service:5672"
  ConnectionStrings__webhooksdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.webhooks_api.postgres_password }};Database=webhooksdb"
  WEBHOOKSDB_PASSWORD: "{{ .Values.secrets.webhooks_api.postgres_password }}"
  WEBHOOKSDB_URI: "postgresql://postgres:{{ .Values.secrets.webhooks_api.postgres_password }}@postgres-service:5432/webhooksdb"
type: "Opaque"
