---
apiVersion: v1
kind: Namespace
metadata:
  name: ruby-cve-2018-3760
---
apiVersion: v1
kind: Service
metadata:
  name: ruby
  namespace: ruby-cve-2018-3760
spec:
  selector:
    app: ruby
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby
  namespace: ruby-cve-2018-3760
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      labels:
        app: ruby
    spec:
      containers:
        - name: ruby
          image: docker.io/vulhub/rails:5.0.7@sha256:42655c82cfb23067a2057da6fea7d72115fd4175eb0c7a2ffb6918220e13a284
          ports:
            - containerPort: 3000
