---
apiVersion: v1
kind: Namespace
metadata:
  name: my-nextjs-ts-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-ts-app
  namespace: my-nextjs-ts-app
spec:
  selector:
    app: my-nextjs-ts-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-ts-app
  namespace: my-nextjs-ts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextjs-ts-app
  template:
    metadata:
      labels:
        app: my-nextjs-ts-app
    spec:
      containers:
        - name: my-nextjs-ts-app
          image: docker.io/danielpacak/my-nextjs-ts-app:node20-bullseye
          ports:
            - containerPort: 3000
