---
apiVersion: v1
kind: Namespace
metadata:
  name: php-cacti-cve-2023-39361
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: php-cacti-cve-2023-39361
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: php-cacti-cve-2023-39361
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: docker.io/library/mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: cacti
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: php-cacti-cve-2023-39361
data:
  entrypoint.sh: |
    #!/bin/bash
    set -ex

    wait-for-it db:3306 -t 300 -- echo "database is connected"
    if [[ ! $(mysql --host=db --user=root --password=root cacti -e "show tables") =~ "automation_devices" ]]; then
    mysql --host=db --user=root --password=root cacti < /var/www/html/cacti.sql
    mysql --host=db --user=root --password=root cacti -e "UPDATE user_auth SET must_change_password='' WHERE username = 'admin'"
    mysql --host=db --user=root --password=root cacti -e "SET GLOBAL time_zone = 'UTC'"
    fi

    # first arg is `-f` or `--some-option`
    if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
    fi

    exec "$@"
---
apiVersion: v1
kind: Service
metadata:
  name: cacti
  namespace: php-cacti-cve-2023-39361
spec:
  selector:
    app: cacti
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacti
  namespace: php-cacti-cve-2023-39361
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cacti
  template:
    metadata:
      labels:
        app: cacti
    spec:
      containers:
        - name: cacti
          image: docker.io/vulhub/cacti:1.2.24
          command:
            - bash
            - /scripts/entrypoint.sh
          args:
            - apache2-foreground
          ports:
            - containerPort: 80
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: scripts
