---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "catalog-api-secrets"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "catalog-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__eventbus: "amqp://guest:{{ .Values.secrets.catalog_api.eventbus_password }}@eventbus-service:5672"
  EVENTBUS_PASSWORD: "{{ .Values.secrets.catalog_api.eventbus_password }}"
  EVENTBUS_URI: "amqp://guest:{{ .Values.secrets.catalog_api.eventbus_password }}@eventbus-service:5672"
  ConnectionStrings__catalogdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.catalog_api.postgres_password }};Database=catalogdb"
  CATALOGDB_PASSWORD: "{{ .Values.secrets.catalog_api.postgres_password }}"
  CATALOGDB_URI: "postgresql://postgres:{{ .Values.secrets.catalog_api.postgres_password }}@postgres-service:5432/catalogdb"
type: "Opaque"
