---
apiVersion: v1
kind: Namespace
metadata:
  name: solr-log4j-cve-2021-44228
---
apiVersion: v1
kind: Service
metadata:
  name: solr
  namespace: solr-log4j-cve-2021-44228
spec:
  selector:
    app: solr
  ports:
    - name: xx
      port: 8983
      targetPort: 8983
      protocol: TCP
    - name: yy
      port: 5005
      targetPort: 5005
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  namespace: solr-log4j-cve-2021-44228
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - image: docker.io/vulhub/solr:8.11.0
          imagePullPolicy: IfNotPresent
          name: solr
          ports:
            - name: http-port
              containerPort: 8983
              protocol: TCP
            - name: jnlp-port
              containerPort: 5005
              protocol: TCP
