---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-express
---
apiVersion: v1
kind: Service
metadata:
  name: hello-express
  namespace: hello-express
spec:
  selector:
    app: hello-express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-express
  namespace: hello-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-express
  template:
    metadata:
      labels:
        app: hello-express
    spec:
      containers:
        - name: hello-express
          image: docker.io/danielpacak/hello-express:node20-bullseye
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
