---
apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin-cve-2023-5002
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: pgadmin-cve-2023-5002
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin-cve-2023-5002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: docker.io/danielpacak/vulhub-pgadmin:7.6
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            - name: logs
              mountPath: /var/log/pgadmin
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}
        - name: logs
          emptyDir: {}
