---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-cve-2021-43798
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana-cve-2021-43798
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana-cve-2021-43798
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: vulhub/grafana:8.2.6
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - name: http-port
              containerPort: 3000
              protocol: TCP
