---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-cve-2024-23897
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-cve-2024-23897
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-cve-2024-23897
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: vulhub/jenkins:2.441
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
            - name: jnlp-port
              containerPort: 50000
              protocol: TCP
            - name: tbd
              containerPort: 5005
              protocol: TCP

