---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "identity-api-secrets"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "identity-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__identitydb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.identity_api.postgres_password }};Database=identitydb"
  IDENTITYDB_PASSWORD: "{{ .Values.secrets.identity_api.postgres_password }}"
  IDENTITYDB_URI: "postgresql://postgres:{{ .Values.secrets.identity_api.postgres_password }}@postgres-service:5432/identitydb"
type: "Opaque"
