---
apiVersion: v1
kind: Namespace
metadata:
  name: mirth
---
apiVersion: v1
kind: Secret
metadata:
  name: mirth-db
  namespace: mirth
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "demo-db"
  port: "5432"
  database: "mirthdb"
  username: "user"
  password: "pass"
---
apiVersion: v1
kind: Service
metadata:
  name: mirth-db
  namespace: mirth
spec:
  ports:
    - port: 5432
  selector:
    app: mirth-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirth-db
  namespace: mirth
  labels:
    app: mirth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirth-db
  template:
    metadata:
      labels:
        app: mirth-db
    spec:
      containers:
        - image: postgres:17
          name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mirth-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mirth-db
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mirth-db
                  key: database
          ports:
            - containerPort: 5432
              name: postgresql
          livenessProbe:
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          startupProbe:
            tcpSocket:
              port: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: mirth-connect
  namespace: mirth
  labels:
    app: mirth-connect
spec:
  selector:
    app: mirth-connect
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8443
    - name: hl7-test
      port: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirth-connect
  namespace: mirth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirth-connect
  template:
    metadata:
      labels:
        app: mirth-connect
    spec:
      containers:
        - name: mirth-connect
          image: "nextgenhealthcare/connect:4.5@sha256:9965c8190ea2e412f754f293920f01da48d44f84383459c63bf19de8fa93e11f"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: DATABASE
              value: postgres
            - name: DATABASE_URL
              value: jdbc:postgresql://mirth-db.mirth.svc.cluster.local:5432/mirthdb
            - name: DATABASE_MAX_CONNECTIONS
              value: "100"
            - name: VMOPTIONS
              value: "-Xmx512m"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mirth-db
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mirth-db
                  key: password
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: hl7-test
              containerPort: 9001