parameters:
  identity_api:
    port_http: 8080
    identity_api_image: "identity-api:latest"
  basket_api:
    port_http: 8080
    basket_api_image: "basket-api:latest"
  catalog_api:
    port_http: 8080
    catalog_api_image: "catalog-api:latest"
  ordering_api:
    port_http: 8080
    ordering_api_image: "ordering-api:latest"
  order_processor:
    port_http: 8080
    order_processor_image: "order-processor:latest"
  payment_processor:
    port_http: 8080
    payment_processor_image: "payment-processor:latest"
  webhooks_api:
    port_http: 8080
    webhooks_api_image: "webhooks-api:latest"
  webhooksclient:
    port_http: 8080
    webhooksclient_image: "webhooksclient:latest"
  webapp:
    port_http: 8080
    webapp_image: "webapp:latest"
secrets:
  redis:
    REDIS_PASSWORD: ""
  eventbus:
    RABBITMQ_DEFAULT_PASS: ""
  postgres:
    POSTGRES_PASSWORD: ""
config:
  eventbus:
    RABBITMQ_DEFAULT_USER: "guest"
  postgres:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  identity_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    IDENTITYDB_HOST: "postgres-service"
    IDENTITYDB_PORT: "5432"
    IDENTITYDB_USERNAME: "postgres"
    IDENTITYDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/identitydb"
    IDENTITYDB_DATABASENAME: "identitydb"
  basket_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    REDIS_HOST: "redis-service"
    REDIS_PORT: "6379"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
  catalog_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
    CATALOGDB_HOST: "postgres-service"
    CATALOGDB_PORT: "5432"
    CATALOGDB_USERNAME: "postgres"
    CATALOGDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/catalogdb"
    CATALOGDB_DATABASENAME: "catalogdb"
  ordering_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
    ORDERINGDB_HOST: "postgres-service"
    ORDERINGDB_PORT: "5432"
    ORDERINGDB_USERNAME: "postgres"
    ORDERINGDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/orderingdb"
    ORDERINGDB_DATABASENAME: "orderingdb"
  order_processor:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
    ORDERINGDB_HOST: "postgres-service"
    ORDERINGDB_PORT: "5432"
    ORDERINGDB_USERNAME: "postgres"
    ORDERINGDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/orderingdb"
    ORDERINGDB_DATABASENAME: "orderingdb"
  payment_processor:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
  webhooks_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
    WEBHOOKSDB_HOST: "postgres-service"
    WEBHOOKSDB_PORT: "5432"
    WEBHOOKSDB_USERNAME: "postgres"
    WEBHOOKSDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/webhooksdb"
    WEBHOOKSDB_DATABASENAME: "webhooksdb"
  mobile_bff:
    ASPNETCORE_ENVIRONMENT: "Production"
    REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/catalog-api/api/catalog/items"
    REVERSEPROXY__ROUTES__route0__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route0__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route0__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route0__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route0__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route0__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/catalog-api/api/catalog/items/by"
    REVERSEPROXY__ROUTES__route1__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route1__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route1__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route1__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route1__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route2__MATCH__PATH: "/catalog-api/api/catalog/items/{id}"
    REVERSEPROXY__ROUTES__route2__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route2__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route2__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route2__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route2__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route2__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route3__MATCH__PATH: "/catalog-api/api/catalog/items/by/{name}"
    REVERSEPROXY__ROUTES__route3__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route3__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route3__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route3__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route3__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route4__MATCH__PATH: "/catalog-api/api/catalog/items/withsemanticrelevance/{text}"
    REVERSEPROXY__ROUTES__route4__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route4__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route4__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route4__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route4__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route4__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route5__MATCH__PATH: "/catalog-api/api/catalog/items/withsemanticrelevance"
    REVERSEPROXY__ROUTES__route5__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route5__MATCH__QUERYPARAMETERS__0__VALUES__0: "2.0"
    REVERSEPROXY__ROUTES__route5__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route5__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route5__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route6__MATCH__PATH: "/catalog-api/api/catalog/items/type/{typeId}/brand/{brandId?}"
    REVERSEPROXY__ROUTES__route6__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route6__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route6__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route6__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route6__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route6__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route7__MATCH__PATH: "/catalog-api/api/catalog/items/type/all/brand/{brandId?}"
    REVERSEPROXY__ROUTES__route7__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route7__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route7__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route7__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route7__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route7__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route8__MATCH__PATH: "/catalog-api/api/catalog/catalogTypes"
    REVERSEPROXY__ROUTES__route8__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route8__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route8__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route8__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route8__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route8__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route8__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route9__MATCH__PATH: "/catalog-api/api/catalog/catalogBrands"
    REVERSEPROXY__ROUTES__route9__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route9__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route9__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route9__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route9__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route9__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route9__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route10__MATCH__PATH: "/catalog-api/api/catalog/items/{id}/pic"
    REVERSEPROXY__ROUTES__route10__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route10__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route10__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route10__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route10__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route10__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route10__TRANSFORMS__0__PathRemovePrefix: "/catalog-api"
    REVERSEPROXY__ROUTES__route11__MATCH__PATH: "/api/catalog/{*any}"
    REVERSEPROXY__ROUTES__route11__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route11__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route11__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route11__MATCH__QUERYPARAMETERS__0__VALUES__2: "2.0"
    REVERSEPROXY__ROUTES__route11__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route11__CLUSTERID: "cluster_catalog-api"
    REVERSEPROXY__ROUTES__route12__MATCH__PATH: "/api/orders/{*any}"
    REVERSEPROXY__ROUTES__route12__MATCH__QUERYPARAMETERS__0__NAME: "api-version"
    REVERSEPROXY__ROUTES__route12__MATCH__QUERYPARAMETERS__0__VALUES__0: "1.0"
    REVERSEPROXY__ROUTES__route12__MATCH__QUERYPARAMETERS__0__VALUES__1: "1"
    REVERSEPROXY__ROUTES__route12__MATCH__QUERYPARAMETERS__0__ISCASESENSITIVE: "False"
    REVERSEPROXY__ROUTES__route12__CLUSTERID: "cluster_ordering-api"
    REVERSEPROXY__ROUTES__route13__MATCH__PATH: "/identity/{*any}"
    REVERSEPROXY__ROUTES__route13__CLUSTERID: "cluster_identity-api"
    REVERSEPROXY__ROUTES__route13__TRANSFORMS__0__PathRemovePrefix: "/identity"
    REVERSEPROXY__CLUSTERS__cluster_catalog_api__DESTINATIONS__destination1__ADDRESS: "https+http://catalog-api"
    REVERSEPROXY__CLUSTERS__cluster_ordering_api__DESTINATIONS__destination1__ADDRESS: "http://_http.ordering-api"
    REVERSEPROXY__CLUSTERS__cluster_identity_api__DESTINATIONS__destination1__ADDRESS: "http://_http.identity-api"
  webhooksclient:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  webapp:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    EVENTBUS_HOST: "eventbus-service"
    EVENTBUS_PORT: "5672"
    EVENTBUS_USERNAME: "guest"
