---
apiVersion: v1
kind: Namespace
metadata:
  name: phpmyadmin-cve-2018-12613
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-mysql
  namespace: phpmyadmin-cve-2018-12613
spec:
  selector:
    app: phpmyadmin-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-mysql
  namespace: phpmyadmin-cve-2018-12613
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-mysql
  template:
    metadata:
      labels:
        app: phpmyadmin-mysql
    spec:
      containers:
        - name: mysql
          image: docker.io/library/mysql:8
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: test
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: phpmyadmin-cve-2018-12613
data:
  config.inc.php: |
    <?php
    /*
     * Generated configuration file
     * Generated by: phpMyAdmin 4.6.2 setup script
     * Date: Mon, 07 May 2018 10:48:03 +0000
     */

    /* Servers configuration */
    $i = 0;

    /* Server: mysql [1] */
    $i++;
    $cfg['Servers'][$i]['verbose'] = 'mysql';
    $cfg['Servers'][$i]['host'] = 'phpmyadmin-mysql';
    $cfg['Servers'][$i]['port'] = 3306;
    $cfg['Servers'][$i]['socket'] = '';
    $cfg['Servers'][$i]['connect_type'] = 'tcp';
    $cfg['Servers'][$i]['auth_type'] = 'config';
    $cfg['Servers'][$i]['user'] = 'test';
    $cfg['Servers'][$i]['password'] = 'test';

    /* End of servers configuration */

    $cfg['blowfish_secret'] = '5af02eda401ae8.69737537';
    $cfg['DefaultLang'] = 'en';
    $cfg['ServerDefault'] = 1;
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: phpmyadmin-cve-2018-12613
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: phpmyadmin-cve-2018-12613
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: docker.io/danielpacak/vulhub-phpmyadmin:4.8.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: scripts
              mountPath: /var/www/html/config.inc.php
              subPath: config.inc.php
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: scripts
