---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-fastapi-python3-13
---
apiVersion: v1
kind: Service
metadata:
  name: hello-fastapi
  namespace: hello-fastapi-python3-13
  labels:
    app: hello-fastapi
spec:
  type: ClusterIP
  selector:
    app: hello-fastapi
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fastapi
  namespace: hello-fastapi-python3-13
  labels:
    app: hello-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-fastapi
  template:
    metadata:
      labels:
        app: hello-fastapi
    spec:
      containers:
        - name: hello-fastapi
          image: docker.io/danielpacak/python-hello-fastapi:python3.13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            httpGet:
              path: /health
              port: 8000
