---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-flask-python-310
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  namespace: hello-flask-python-310
  labels:
    app: hello-flask
spec:
  type: ClusterIP
  selector:
    app: hello-flask
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  namespace: hello-flask-python-310
  labels:
    app: hello-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
        - name: hello-flask
          image: docker.io/danielpacak/python-hello-flask:python3.10-glibc
          imagePullPolicy: IfNotPresent
          env:
            - name: HELLO_FLASK_MEMORY_BYTES
              value: "512"
            - name: HELLO_FLASK_DYNAMIC_RULES_COUNT
              value: "10"
          ports:
            - containerPort: 5050
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            httpGet:
              path: /health
              port: 5050
