---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "eventbus-config"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "eventbus"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.config.eventbus.RABBITMQ_DEFAULT_USER }}"
