---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "eventbus-secrets"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "eventbus"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  RABBITMQ_DEFAULT_PASS: "{{ .Values.secrets.eventbus.eventbus_password }}"
type: "Opaque"
