---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "basket-api-config"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "basket-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.basket_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.basket_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.basket_api.port_http }}"
  REDIS_HOST: "{{ .Values.config.basket_api.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.config.basket_api.REDIS_PORT }}"
  EVENTBUS_HOST: "{{ .Values.config.basket_api.EVENTBUS_HOST }}"
  EVENTBUS_PORT: "{{ .Values.config.basket_api.EVENTBUS_PORT }}"
  EVENTBUS_USERNAME: "{{ .Values.config.basket_api.EVENTBUS_USERNAME }}"
  Identity__Url: "https://identity-api-service:{{ .Values.parameters.identity_api.port_http }}"
