---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "basket-api-secrets"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "basket-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__redis: "redis-service:6379,password={{ .Values.secrets.basket_api.redis_password }}"
  REDIS_PASSWORD: "{{ .Values.secrets.basket_api.redis_password }}"
  REDIS_URI: "redis://:{{ .Values.secrets.basket_api.redis_password }}@redis-service:6379"
  ConnectionStrings__eventbus: "amqp://guest:{{ .Values.secrets.basket_api.eventbus_password }}@eventbus-service:5672"
  EVENTBUS_PASSWORD: "{{ .Values.secrets.basket_api.eventbus_password }}"
  EVENTBUS_URI: "amqp://guest:{{ .Values.secrets.basket_api.eventbus_password }}@eventbus-service:5672"
type: "Opaque"
