---
apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin-cve-2023-5002
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: pgadmin-cve-2023-5002
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin-cve-2023-5002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: docker.io/vulhub/pgadmin:7.6@sha256:efbd4438dd0b9832ec0be07d08a83100b8cee8b74b26330c8560a6b9005f5788
          ports:
            - containerPort: 5050
