---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-flask-python-39
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-flask
  namespace: hello-flask-python-39
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-flask-python-39
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hello-flask-python-39
subjects:
- kind: ServiceAccount
  name: hello-flask
  namespace: hello-flask-python-39
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hello-flask-python-39
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  namespace: hello-flask-python-39
  labels:
    app: hello-flask
spec:
  type: ClusterIP
  selector:
    app: hello-flask
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  namespace: hello-flask-python-39
  labels:
    app: hello-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      serviceAccountName: hello-flask
      automountServiceAccountToken: true
      containers:
        - name: hello-flask
          image: docker.io/danielpacak/python-hello-flask:python3.9-glibc
          imagePullPolicy: IfNotPresent
          env:
            - name: HELLO_FLASK_MEMORY_BYTES
              value: "512"
            - name: HELLO_FLASK_DYNAMIC_RULES_COUNT
              value: "10"
            - name: PYROSCOPE_APPLICATION_NAME
              value: "hello-flask-python3.9"
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://pyroscope.pyroscope:4040"
          ports:
            - containerPort: 5050
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            httpGet:
              path: /health
              port: 5050
