---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "webapp-config"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "webapp"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.webapp.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.webapp.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.webapp.port_http }}"
  BASKET_API_HTTP: "http://basket-api-service:{{ .Values.parameters.basket_api.port_http }}"
  services__basket-api__http__0: "http://basket-api-service:{{ .Values.parameters.basket_api.port_http }}"
  BASKET_API_HTTPS: "https://basket-api-service:{{ .Values.parameters.basket_api.port_http }}"
  services__basket-api__https__0: "https://basket-api-service:{{ .Values.parameters.basket_api.port_http }}"
  CATALOG_API_HTTP: "http://catalog-api-service:{{ .Values.parameters.catalog_api.port_http }}"
  services__catalog-api__http__0: "http://catalog-api-service:{{ .Values.parameters.catalog_api.port_http }}"
  CATALOG_API_HTTPS: "https://catalog-api-service:{{ .Values.parameters.catalog_api.port_http }}"
  services__catalog-api__https__0: "https://catalog-api-service:{{ .Values.parameters.catalog_api.port_http }}"
  ORDERING_API_HTTP: "http://ordering-api-service:{{ .Values.parameters.ordering_api.port_http }}"
  services__ordering-api__http__0: "http://ordering-api-service:{{ .Values.parameters.ordering_api.port_http }}"
  ORDERING_API_HTTPS: "https://ordering-api-service:{{ .Values.parameters.ordering_api.port_http }}"
  services__ordering-api__https__0: "https://ordering-api-service:{{ .Values.parameters.ordering_api.port_http }}"
  EVENTBUS_HOST: "{{ .Values.config.webapp.EVENTBUS_HOST }}"
  EVENTBUS_PORT: "{{ .Values.config.webapp.EVENTBUS_PORT }}"
  EVENTBUS_USERNAME: "{{ .Values.config.webapp.EVENTBUS_USERNAME }}"
  IdentityUrl: "https://identity-api-service:{{ .Values.parameters.identity_api.port_http }}"
  CallBackUrl: "https://webapp-service:{{ .Values.parameters.webapp.port_http }}"
