---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "webapp-secrets"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "webapp"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__eventbus: "amqp://guest:{{ .Values.secrets.webapp.eventbus_password }}@eventbus-service:5672"
  EVENTBUS_PASSWORD: "{{ .Values.secrets.webapp.eventbus_password }}"
  EVENTBUS_URI: "amqp://guest:{{ .Values.secrets.webapp.eventbus_password }}@eventbus-service:5672"
type: "Opaque"
