---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "webapp-service"
  labels:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "webapp"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "eshop-apphost"
    app.kubernetes.io/component: "webapp"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.webapp.port_http | int }}
      targetPort: {{ .Values.parameters.webapp.port_http | int }}
